

import Footer from "./common-components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";


export const metadata = {
  title: "FaInstagram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
